// ============================================================
// Tree Source — Filling A Container From A Repository, Within Budget
// ============================================================
// The workspace is a LAZY overlay: it holds the files something has actually
// asked for, which is the right shape for type checking and the wrong one for
// `npm test`. A test runner walks the project; a project missing nine tenths of
// its files fails for a reason that has nothing to do with the change, and the
// agent then reports that failure as if it were real.
//
// So the container's tree is hydrated from the repository listing instead — with
// every bound stated, and every omission reported. The rule this module is built
// around is the one the rest of the feature follows: silence about a partial tree
// is how a passing subset is mistaken for a passing suite.
//
// What is never fetched, and why:
//
//   • `node_modules/` — the install creates it, and a repo that commits it would
//     be mounting a stale copy of something the install is about to replace.
//   • build outputs (`dist/`, `build/`, `out/`, `.next/`, `coverage/`) — they are
//     regenerated by the very commands this tier runs, and they are large.
//   • `.git/` — not data, and the container has no git.
//   • binaries by extension, and anything over the per-file ceiling — assets
//     ARE fetched, but as BYTES through `readBinary` (the preview serves them;
//     a restaurant site without its photos is a broken page, not a preview).
//     Only per-asset size caps and anything over the byte budget are skipped.
//   • secret-shaped paths — decided once, in mount-plan.ts, but skipped early
//     here too so the bytes are never even fetched.
//
// Reads go through an injected `read` so this stays testable without a network,
// and so the caller decides what a failure to read MEANS (a 404 and a rate limit
// are the same shape at this layer, and different problems to a user).
// ============================================================

import { classifyPath } from "../lib/sensitivity";

export interface TreeEntryLike {
  path: string;
  type: string;
  size?: number;
}

/** Files hydrated for one mount. Below the mount ceiling, leaving room for edits */
export const HYDRATE_MAX_FILES = 900;
/** Total bytes hydrated. The container is a tab, not a disk */
export const HYDRATE_MAX_BYTES = 8 * 1024 * 1024;
/** One file's ceiling for TEXT: beyond this it is data, not source */
export const HYDRATE_MAX_FILE_BYTES = 512 * 1024;
/** One asset's ceiling for BYTES: generous for a photo, fatal for a video */
export const HYDRATE_MAX_ASSET_BYTES = 2 * 1024 * 1024;
/** Parallel reads: enough to hide latency, few enough to stay inside rate limits */
export const HYDRATE_CONCURRENCY = 6;

/** Paths never fetched. Each one is reported, so a mystery failure is traceable. */
const EXCLUDED_PREFIXES: { pattern: RegExp; reason: string }[] = [
  { pattern: /^node_modules\//, reason: "dependencies are installed by the workspace, not fetched" },
  { pattern: /^\.git\//, reason: "git metadata is not source, and the container has no git" },
  { pattern: /^(dist|build|out|\.next|\.nuxt|\.output|coverage)\//, reason: "build output is regenerated by the commands this tier runs" },
];

/**
 * Extensions fetched as BYTES through `readBinary`, not skipped.
 *
 * Images, fonts, and audio are what a preview is FOR — the most common way a
 * real site is broken is its assets missing, which reads as a broken project
 * rather than a partial mount. Never-fetched classes stay excluded outright:
 * executables and archives (`zip|gz|exe|wasm…`) have no role inside a browser
 * workspace that installs its own dependencies, documents are not served by a
 * dev server this tier runs, and media beyond the asset cap (video) is a byte
 * budget the tab cannot spare.
 */
const BINARY_ASSET =
  /\.(png|jpe?g|gif|webp|avif|ico|bmp|svgz|woff2?|ttf|otf|eot|mp3|wav|ogg|flac)$/i;

/**
 * Files hydrated ahead of every cap, because the workspace's own decisions read
 * them. Which script starts this project, which package manager installs it,
 * and whether the lockfile can pin the install are all answered from these
 * names — losing `package.json` to a byte budget spent on photographs is how an
 * image-heavy Next.js repo surfaced as "declares no dev/start/serve/preview
 * script": the manifest was never absent, it was unfetched. They still count
 * toward the file budget and their bytes still count against the budget for
 * everything else; they are only exempt from being DROPPED by it, and the text
 * per-file ceiling bounds them regardless.
 */
const CRITICAL_MANIFESTS = ["package.json", "package-lock.json"] as const;

/** Extensions never fetched, in any form, with the reason a reader gets */
const BINARY_EXCLUDED: { pattern: RegExp; reason: string }[] = [
  { pattern: /\.(mp4|webm|mov|avi|mkv)$/i, reason: "video is beyond this workspace's byte budget" },
  { pattern: /\.(zip|gz|tgz|bz2|xz|7z|rar|jar|wasm|exe|dll|so|dylib|node|bin|dat|sqlite3?|db|pack|class|pyc|onnx|pt|safetensors)$/i, reason: "an executable or archive cannot run or be read in a browser workspace" },
  { pattern: /\.(pdf|docx?|xlsx?|pptx?)$/i, reason: "a document is not part of what a dev server serves here" },
];

export interface HydrateSkip {
  path: string;
  reason: string;
}

export interface HydratedTree {
  /** Base files, ready to compose with the change set (bytes for binary assets) */
  base: { path: string; content: string | Uint8Array }[];
  /** Entries deliberately not fetched, with the reason */
  skipped: HydrateSkip[];
  /** Entries the listing has but the reader could not produce */
  unread: HydrateSkip[];
  bytes: number;
  /** False when a ceiling was hit, so the tree is a PREFIX of the repository */
  complete: boolean;
  /** Lines the caller must surface — never optional reading */
  notes: string[];
}

/**
 * Fetches the repository's text files, bounded three ways.
 *
 * `read` resolves to null when a file cannot be read as text (binary, too large,
 * not found) — that is a normal outcome and is counted, not thrown.
 */
export async function hydrateTree(input: {
  entries: readonly TreeEntryLike[];
  read: (path: string) => Promise<string | null>;
  /**
   * Reads one binary asset as raw bytes, or null when it cannot.
   *
   * Absent hook means binary assets are skipped as before — the hook is what
   * makes the preview able to show them, and a caller that cannot fetch bytes
   * (no token, a read-only cache) says so through its own absence.
   */
  readBinary?: (path: string) => Promise<Uint8Array | null>;
  maxFiles?: number;
  maxBytes?: number;
  maxFileBytes?: number;
  maxAssetBytes?: number;
  concurrency?: number;
}): Promise<HydratedTree> {
  const maxFiles = input.maxFiles ?? HYDRATE_MAX_FILES;
  const maxBytes = input.maxBytes ?? HYDRATE_MAX_BYTES;
  const maxFileBytes = input.maxFileBytes ?? HYDRATE_MAX_FILE_BYTES;
  const maxAssetBytes = input.maxAssetBytes ?? HYDRATE_MAX_ASSET_BYTES;

  const candidates: string[] = [];
  const assets: string[] = [];
  const skipped: HydrateSkip[] = [];
  for (const entry of input.entries) {
    if (entry.type !== "blob") continue;
    const excluded = EXCLUDED_PREFIXES.find((rule) => rule.pattern.test(entry.path));
    if (excluded) {
      skipped.push({ path: entry.path, reason: excluded.reason });
      continue;
    }
    if (classifyPath(entry.path) === "secret") {
      skipped.push({ path: entry.path, reason: "secret-shaped path: never fetched into a workspace" });
      continue;
    }
    // Binary assets are a different CLASS from here on: fetched as bytes, with
    // their own ceiling and their own reader. The exclusion list above it is the
    // set that is never fetched in any form.
    if (BINARY_ASSET.test(entry.path)) {
      if (!input.readBinary) {
        skipped.push({ path: entry.path, reason: "binary asset: no byte reader available for this mount" });
        continue;
      }
      if (typeof entry.size === "number" && entry.size > maxAssetBytes) {
        skipped.push({ path: entry.path, reason: `over ${Math.round(maxAssetBytes / 1024)} KiB asset cap` });
        continue;
      }
      assets.push(entry.path);
      continue;
    }
    for (const rule of BINARY_EXCLUDED) {
      if (rule.pattern.test(entry.path)) {
        skipped.push({ path: entry.path, reason: rule.reason });
        break;
      }
    }
    if (BINARY_EXCLUDED.some((rule) => rule.pattern.test(entry.path))) continue;
    if (typeof entry.size === "number" && entry.size > maxFileBytes) {
      skipped.push({ path: entry.path, reason: `over ${Math.round(maxFileBytes / 1024)} KiB` });
      continue;
    }
    candidates.push(entry.path);
  }

  // Path order, so a cap that bites always bites in the same place.
  candidates.sort((a, b) => a.localeCompare(b));
  // The manifests take the first seats; the remaining file budget is theirs to
  // spend last. Selection — not a tail slice — decides what is skipped: a tail
  // slice of the sorted list can land on a manifest itself in a repo with few
  // files that sort after `package.json`.
  const critical = candidates.filter((path) => (CRITICAL_MANIFESTS as readonly string[]).includes(path));
  const ordinary = candidates.filter((path) => !(CRITICAL_MANIFESTS as readonly string[]).includes(path));
  const selected = [...critical, ...ordinary.slice(0, Math.max(0, maxFiles - critical.length))];
  const overFileCap = candidates.length - selected.length;
  const selectedSet = new Set(selected);
  for (const path of candidates) {
    if (!selectedSet.has(path)) skipped.push({ path, reason: `beyond the ${maxFiles}-file budget` });
  }

  // What the listing says each candidate WEIGHS, for the emptiness check below.
  const listedBytes = new Map<string, number>();
  for (const entry of input.entries) {
    if (entry.type === "blob" && typeof entry.size === "number") listedBytes.set(entry.path, entry.size);
  }

  const unread: HydrateSkip[] = [];
  const base: { path: string; content: string | Uint8Array }[] = [];
  let bytes = 0;
  let overByteCap = 0;
  // Counted apart from the text overage: the note names "candidate files" and
  // assets were never candidates, so folding them into one number produced a
  // note that could claim more files were dropped than the listing held.
  let assetOverByteCap = 0;

  // Assets hydrate first: a byte budget spent on text before photos means the
  // preview's images are the things dropped, and the images are what the user
  // SEES missing. The budget is shared, so text still wins when it would not
  // both fit — but the cap order says which loss is the acceptable one.
  await pool(assets, input.concurrency ?? HYDRATE_CONCURRENCY, async (path) => {
    const bytes8 = await input.readBinary!(path);
    if (bytes8 === null || bytes8.byteLength === 0) {
      unread.push({ path, reason: "the asset's bytes could not be read" });
      return;
    }
    if (bytes + bytes8.byteLength > maxBytes) {
      assetOverByteCap += 1;
      skipped.push({ path, reason: `beyond the ${Math.round(maxBytes / (1024 * 1024))} MiB byte budget` });
      return;
    }
    bytes += bytes8.byteLength;
    base.push({ path, content: bytes8 });
  });

  await pool(selected, input.concurrency ?? HYDRATE_CONCURRENCY, async (path) => {
    const content = await input.read(path);
    if (content === null) {
      unread.push({ path, reason: "the reader returned no text (binary, too large, or unavailable)" });
      return;
    }
    // An empty read for a non-empty blob is a FAILED read, not an empty file.
    //
    // This check exists because of what an empty file does downstream: the path
    // is still in the tree, so every name-based decision about the revision is
    // made as if the file were there (the install plan reads a `package-lock.json`
    // that is present and picks the frozen `npm ci`, the dev script is found in a
    // `package.json` that parsed), while the BYTES in the workspace are the empty
    // string. The mismatch surfaces much later and in the wrong place — `npm ci`
    // answers "can only install with an existing package-lock.json", which reads
    // as a broken repository rather than a broken read. Counting it as unread puts
    // the failure where it can be named, and leaves the plan to choose the install
    // that does not depend on the missing bytes.
    const listed = listedBytes.get(path);
    if (content.length === 0 && listed !== undefined && listed > 0) {
      unread.push({
        path,
        reason: `the reader returned an empty file for a blob the listing reports as ${listed} bytes`,
      });
      return;
    }
    // The manifests are dropped by nothing here: an over-budget repo keeps a
    // `package.json` that names its dev script, so the preview answers the
    // question the repo actually declared instead of one the budget forced.
    if (bytes + content.length > maxBytes && !(CRITICAL_MANIFESTS as readonly string[]).includes(path)) {
      overByteCap += 1;
      skipped.push({ path, reason: `beyond the ${Math.round(maxBytes / (1024 * 1024))} MiB byte budget` });
      return;
    }
    bytes += content.length;
    base.push({ path, content });
  });

  base.sort((a, b) => a.path.localeCompare(b.path));
  const complete = overFileCap === 0 && overByteCap === 0 && assetOverByteCap === 0;
  const notes: string[] = [];
  if (!complete) {
    // Every number in this note is about the CANDIDATES — the text files the
    // caps select between, so the frame counts text against candidates rather
    // than all files (assets can push `base.length` past the candidate count,
    // which read as "101 of 115"). Assets were never candidates, so their
    // overage is its own sentence: one number mixing both was how this note
    // once reported "170 beyond the byte budget" for a listing of 115 files.
    const textMounted = base.filter((file) => typeof file.content === "string").length;
    const overParts: string[] = [];
    if (overFileCap > 0) overParts.push(`${overFileCap} beyond the ${maxFiles}-file budget`);
    if (overByteCap > 0) overParts.push(`${overByteCap} beyond the ${Math.round(maxBytes / (1024 * 1024))} MiB byte budget`);
    const overClause = overParts.length > 0 ? ` (${overParts.join(", ")})` : "";
    let note =
      `The workspace holds ${base.length} file(s) from this revision — ${textMounted} of ${candidates.length} candidate text files; it is too large to mount in full${overClause}. A command that needs a file which is not here will fail for that reason, not because of the change — say so rather than reporting that failure as real.`;
    if (assetOverByteCap > 0) {
      note += ` Binary assets share that byte budget and ${assetOverByteCap} of them were left out of the workspace.`;
    }
    notes.push(note);
  }
  if (unread.length > 0) {
    // NAMED, not counted. A count is enough to say the tree is partial, but the
    // only actionable fact is WHICH file is missing — and the failure it causes
    // lands far away from here, in a command that reports something else
    // entirely. Three names is the point where the note stops being read.
    const named = unread
      .slice(0, 3)
      .map((entry) => `\`${entry.path}\` (${entry.reason})`)
      .join("; ");
    notes.push(
      `${unread.length} file(s) could not be read and are not in the workspace: ${named}${unread.length > 3 ? `; +${unread.length - 3} more` : ""}. A command that needs one of them fails for that reason, not because of the change.`
    );
  }

  return { base, skipped, unread, bytes, complete, notes };
}

/** A bounded worker pool — order of results does not matter, order of work does */
async function pool<T>(items: readonly T[], limit: number, run: (item: T) => Promise<void>): Promise<void> {
  let next = 0;
  const workers = Array.from({ length: Math.max(1, Math.min(limit, items.length)) }, async () => {
    for (;;) {
      const index = next;
      next += 1;
      const item = items[index];
      if (item === undefined) return;
      await run(item);
    }
  });
  await Promise.all(workers);
}

/** One line summarizing a hydration, for a tool result */
export function describeHydration(tree: HydratedTree): string {
  const size = tree.bytes >= 1024 * 1024 ? `${(tree.bytes / (1024 * 1024)).toFixed(1)} MiB` : `${Math.round(tree.bytes / 1024)} KiB`;
  const head = `${tree.base.length} file${tree.base.length === 1 ? "" : "s"} (${size}) read from the repository`;
  if (tree.complete && tree.skipped.length === 0) return head;
  return `${head}${tree.complete ? "" : ", PARTIAL"}; ${tree.skipped.length} not fetched, ${tree.unread.length} unreadable.`;
}
