// ============================================================
// Tree Source — Filling A Container From A Repository, Within Budget
// ============================================================
// The workspace is a LAZY overlay: it holds the files something has actually
// asked for, which is the right shape for type checking and the wrong one for
// `npm test`. A test runner walks the project; a project missing nine tenths of
// its files fails for a reason that has nothing to do with the change, and the
// agent then reports that failure as if it were real.
//
// So the container's tree is hydrated from the repository listing instead — with
// every bound stated, and every omission reported. The rule this module is built
// around is the one the rest of the feature follows: silence about a partial tree
// is how a passing subset is mistaken for a passing suite.
//
// What is never fetched, and why:
//
//   • `node_modules/` — the install creates it, and a repo that commits it would
//     be mounting a stale copy of something the install is about to replace.
//   • build outputs (`dist/`, `build/`, `out/`, `.next/`, `coverage/`) — they are
//     regenerated by the very commands this tier runs, and they are large.
//   • `.git/` — not data, and the container has no git.
//   • binaries by extension, and anything over the per-file ceiling — a text
//     mount of a PNG is noise, and the reader returns nothing useful for it.
//   • secret-shaped paths — decided once, in mount-plan.ts, but skipped early
//     here too so the bytes are never even fetched.
//
// Reads go through an injected `read` so this stays testable without a network,
// and so the caller decides what a failure to read MEANS (a 404 and a rate limit
// are the same shape at this layer, and different problems to a user).
// ============================================================

import { classifyPath } from "../lib/sensitivity";

export interface TreeEntryLike {
  path: string;
  type: string;
  size?: number;
}

/** Files hydrated for one mount. Below the mount ceiling, leaving room for edits */
export const HYDRATE_MAX_FILES = 900;
/** Total bytes hydrated. The container is a tab, not a disk */
export const HYDRATE_MAX_BYTES = 8 * 1024 * 1024;
/** One file's ceiling for TEXT: beyond this it is data, not source */
export const HYDRATE_MAX_FILE_BYTES = 512 * 1024;
/** Parallel reads: enough to hide latency, few enough to stay inside rate limits */
export const HYDRATE_CONCURRENCY = 6;

/** Paths never fetched. Each one is reported, so a mystery failure is traceable. */
const EXCLUDED_PREFIXES: { pattern: RegExp; reason: string }[] = [
  { pattern: /^node_modules\//, reason: "dependencies are installed by the workspace, not fetched" },
  { pattern: /^\.git\//, reason: "git metadata is not source, and the container has no git" },
  { pattern: /^(dist|build|out|\.next|\.nuxt|\.output|coverage)\//, reason: "build output is regenerated by the commands this tier runs" },
];

/** Extensions that are data: mounting them as text helps nobody */
const BINARY_EXTENSION =
  /\.(png|jpe?g|gif|webp|avif|ico|bmp|tiff?|woff2?|ttf|otf|eot|mp[34]|wav|ogg|webm|mov|avi|zip|gz|tgz|bz2|xz|7z|rar|pdf|docx?|xlsx?|pptx?|jar|wasm|exe|dll|so|dylib|bin|dat|sqlite3?|db|pack|class|pyc|onnx|pt|safetensors)$/i;

export interface HydrateSkip {
  path: string;
  reason: string;
}

export interface HydratedTree {
  /** Base files, ready to compose with the change set */
  base: { path: string; content: string }[];
  /** Entries deliberately not fetched, with the reason */
  skipped: HydrateSkip[];
  /** Entries the listing has but the reader could not produce */
  unread: HydrateSkip[];
  bytes: number;
  /** False when a ceiling was hit, so the tree is a PREFIX of the repository */
  complete: boolean;
  /** Lines the caller must surface — never optional reading */
  notes: string[];
}

/**
 * Fetches the repository's text files, bounded three ways.
 *
 * `read` resolves to null when a file cannot be read as text (binary, too large,
 * not found) — that is a normal outcome and is counted, not thrown.
 */
export async function hydrateTree(input: {
  entries: readonly TreeEntryLike[];
  read: (path: string) => Promise<string | null>;
  maxFiles?: number;
  maxBytes?: number;
  maxFileBytes?: number;
  concurrency?: number;
}): Promise<HydratedTree> {
  const maxFiles = input.maxFiles ?? HYDRATE_MAX_FILES;
  const maxBytes = input.maxBytes ?? HYDRATE_MAX_BYTES;
  const maxFileBytes = input.maxFileBytes ?? HYDRATE_MAX_FILE_BYTES;

  const candidates: string[] = [];
  const skipped: HydrateSkip[] = [];
  for (const entry of input.entries) {
    if (entry.type !== "blob") continue;
    const excluded = EXCLUDED_PREFIXES.find((rule) => rule.pattern.test(entry.path));
    if (excluded) {
      skipped.push({ path: entry.path, reason: excluded.reason });
      continue;
    }
    if (classifyPath(entry.path) === "secret") {
      skipped.push({ path: entry.path, reason: "secret-shaped path: never fetched into a workspace" });
      continue;
    }
    if (BINARY_EXTENSION.test(entry.path)) {
      skipped.push({ path: entry.path, reason: "binary file: not mounted as text" });
      continue;
    }
    if (typeof entry.size === "number" && entry.size > maxFileBytes) {
      skipped.push({ path: entry.path, reason: `over ${Math.round(maxFileBytes / 1024)} KiB` });
      continue;
    }
    candidates.push(entry.path);
  }

  // Path order, so a cap that bites always bites in the same place.
  candidates.sort((a, b) => a.localeCompare(b));
  const selected = candidates.slice(0, maxFiles);
  const overFileCap = candidates.length - selected.length;
  for (const path of candidates.slice(maxFiles)) {
    skipped.push({ path, reason: `beyond the ${maxFiles}-file budget` });
  }

  const unread: HydrateSkip[] = [];
  const base: { path: string; content: string }[] = [];
  let bytes = 0;
  let overByteCap = 0;

  await pool(selected, input.concurrency ?? HYDRATE_CONCURRENCY, async (path) => {
    const content = await input.read(path);
    if (content === null) {
      unread.push({ path, reason: "the reader returned no text (binary, too large, or unavailable)" });
      return;
    }
    if (bytes + content.length > maxBytes) {
      overByteCap += 1;
      skipped.push({ path, reason: `beyond the ${Math.round(maxBytes / (1024 * 1024))} MiB byte budget` });
      return;
    }
    bytes += content.length;
    base.push({ path, content });
  });

  base.sort((a, b) => a.path.localeCompare(b.path));
  const complete = overFileCap === 0 && overByteCap === 0;
  const notes: string[] = [];
  if (!complete) {
    notes.push(
      `The workspace holds ${base.length} of ${candidates.length} candidate files: this revision is too large to mount in full (${overFileCap} beyond the file budget, ${overByteCap} beyond the byte budget). A command that needs a file which is not here will fail for that reason, not because of the change — say so rather than reporting that failure as real.`
    );
  }
  if (unread.length > 0) {
    notes.push(`${unread.length} file(s) could not be read as text and are not in the workspace.`);
  }

  return { base, skipped, unread, bytes, complete, notes };
}

/** A bounded worker pool — order of results does not matter, order of work does */
async function pool<T>(items: readonly T[], limit: number, run: (item: T) => Promise<void>): Promise<void> {
  let next = 0;
  const workers = Array.from({ length: Math.max(1, Math.min(limit, items.length)) }, async () => {
    for (;;) {
      const index = next;
      next += 1;
      const item = items[index];
      if (item === undefined) return;
      await run(item);
    }
  });
  await Promise.all(workers);
}

/** One line summarizing a hydration, for a tool result */
export function describeHydration(tree: HydratedTree): string {
  const size = tree.bytes >= 1024 * 1024 ? `${(tree.bytes / (1024 * 1024)).toFixed(1)} MiB` : `${Math.round(tree.bytes / 1024)} KiB`;
  const head = `${tree.base.length} file${tree.base.length === 1 ? "" : "s"} (${size}) read from the repository`;
  if (tree.complete && tree.skipped.length === 0) return head;
  return `${head}${tree.complete ? "" : ", PARTIAL"}; ${tree.skipped.length} not fetched, ${tree.unread.length} unreadable.`;
}
